export const db="QnA System"
export const questionCollection="questions"
export const answerCollection="answers"
export const commentCollection="comments"
export const votesCollection="votes"
export const questionAttachmentBucket="question-attachment"